homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: imperial
  temperature_unit: F
  time_zone: !secret tz
  customize: !include includes/customize.yaml

frontend:
history:
logbook:
updater:
  reporting: no


http: !include includes/http.yaml

logger: !include includes/logger.yaml

mqtt: !include includes/mqtt.yaml

notify: !include includes/notify.yaml

recorder: !include includes/recorder.yaml

sun: !include includes/sun.yaml

xiaomi: !include includes/xiaomi.yaml

zwave: !include includes/zwave.yaml


automation: !include_dir_merge_list includes/automations

camera: !include_dir_merge_list includes/cameras

device_tracker: !include_dir_merge_list includes/device_trackers

group: !include_dir_merge_named includes/groups

light: !include_dir_merge_list includes/lights

input_select: !include_dir_merge_named includes/input_selects

input_slider: !include_dir_merge_named includes/input_sliders

scene: !include_dir_merge_list includes/scenes

script: !include_dir_merge_named includes/scripts

sensor: !include_dir_merge_list includes/sensors

shell_command: !include_dir_merge_named includes/shell_commands

switch: !include_dir_merge_list includes/switches

zone: !include_dir_merge_named includes/zones
