- alias: 'Set thermostat fan_mode based on input_select'
  trigger:
    platform: state
    entity_id: input_select.hvac_fan_mode
  action:
    service: climate.set_fan_mode
    entity_id: climate.thermostat_downstairs_cooling_1_2_2
    data_template:
      fan_mode: >-
          {%- if is_state('input_select.hvac_fan_mode', 'Auto') -%}
              Auto Low
          {%- elif is_state('input_select.hvac_fan_mode', 'On') -%}
              On Low
          {%- endif -%}

- alias: 'Set input_select based on thermostat fan_mode'
  trigger:
    platform: state
    entity_id: climate.thermostat_downstairs_cooling_1_2_2
  condition:
    condition: template
    value_template: '{{ trigger.to_state.attributes.fan_mode != trigger.from_state.attributes.fan_mode }}'
  action:
    service: input_select.select_option
    entity_id: input_select.hvac_fan_mode
    data_template:
      option: >-
          {%- if is_state_attr('climate.thermostat_downstairs_cooling_1_2_2', 'fan_mode', 'Auto Low') -%}
              Auto
          {%- elif is_state_attr('climate.thermostat_downstairs_cooling_1_2_2', 'fan_mode', 'On Low') -%}
              On
          {%- endif -%}
