#####
### Send notification if Kitchen Lock is unlocked, and derek_n6p AND andrea_iphone6 are not_home
#####
- alias: 'Lock - Kitchen Notify Unlock'
  trigger:
    - platform: state
      entity_id: lock.deadbolt_kitchen_locked_9_0
      state: 'unlocked'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.phone_derek_pixelxl
        state: not_home
      - condition: state
        entity_id: device_tracker.phone_andrea_pixel
        state: not_home
  action:
    service: notify.pushover
    data_template:
      message: "Kitchen door was just unlocked!"
