#####
### Send notification anytime motion is detected inside gunsafe
#####
- alias: 'Gun Safe Motion Notify'
  trigger:
    - platform: state
      entity_id: binary_sensor.multisensor_gunsafe_sensor_23_0
      state: 'on'
  action:
    service: notify.pushover
    data_template:
      message: "Somebody opened your gun safe; AAAHHHH!!!"

#####
### Send notification anytime door is opened on ammosafe
#####
- alias: 'Ammo Safe door-open Notify'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_ammosafe_sensor_33_0
      state: 'on'
  action:
    service: notify.pushover
    data_template:
      message: "Somebody opened your ammo safe; AAAHHHH!!!"

#####
### Send notification anytime door is opened on officesafe
#####
- alias: 'Office Safe door-open Notify'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_officesafe_sensor_41_0
      state: 'on'
  action:
    service: notify.pushover
    data_template:
      message: "Somebody opened your office safe; AAAHHHH!!!"
