- alias: 'TV Room Lamp On'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    condition: state
    entity_id: switch.lamp_tvroom_switch_22_0
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.lamp_tvroom_switch_22_0

- alias: 'TV Room Lamp Off'
  trigger:
    platform: time
    after: '00:15'
  condition:
    condition: state
    entity_id: switch.lamp_tvroom_switch_22_0
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_tvroom_switch_22_0
