#####
### Turn on Fish Tank lamp at 08:48AM, if it's off
#####
- alias: 'Fish Tank Lamp On'
  trigger:
    platform: time
    after: '08:48'
  condition:
    condition: state
    entity_id: switch.lamp_fisktank_switch_24_0
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.lamp_fishtank_switch_24_0

#####
### Turn off Fish Tank lamp at 11:11PM, if it's on
#####
- alias: 'Fish Tank Lamp Off'
  trigger:
    platform: time
    after: '11:11'
  condition:
    condition: state
    entity_id: switch.lamp_fishtank_switch_24_0
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_fishtank_switch_24_0
