#####
### Turn on Dining Room lamp 30 minutes before sunset, if it's off
#####
- alias: 'Dining Room Lamp On'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    condition: state
    entity_id: switch.lamp_diningroom_switch_20_0
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.lamp_diningroom_switch_20_0

#####
### Turn off Dining Room lamp at 12:15AM, if it's on and the TV Room lamp is off
### First try
#####
- alias: 'Dining Room Lamp Off'
  trigger:
    platform: time
    after: '00:15'
  condition:
    condition: 'and'
    conditions:
      - condition: state
        entity_id: switch.lamp_diningroom_switch_20_0
        state: 'on'
      - condition: state
        entity_id: switch.lamp_tvroom_switch_22_0
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_diningroom_switch_20_0

#####
### Turn off Dining Room lamp at 01:14AM, if it's on and the TV Room lamp is off
### Second try in case the lamp doesn't get turned off during the first try
#####
- alias: 'Dining Room Lamp Off (second try)'
  trigger:
    platform: time
    after: '01:15'
  condition:
    condition: 'and'
    conditions:
      - condition: state
        entity_id: switch.lamp_diningroom_switch_20_0
        state: 'on'
      - condition: state
        entity_id: switch.lamp_tvroom_switch_22_0
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_diningroom_switch_20_0
