#####
### Turn on Garage Exterior Lights at sunset, if it's off
#####
- alias: 'Garage Exterior Lights On'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: switch.garage_exterior_lights
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.garage_exterior_lights


#####
### Turn off Garage Exterior Lights at 01:03AM, if it's on and both device_trackers are home
#####
- alias: 'Garage Exterior Lights Off (at home)'
  trigger:
    platform: time
    after: '01:03'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.garage_exterior_lights
        state: 'on'
      - condition: state
        entity_id: device_tracker.phone_derek_pixelxl
        state: 'home'
      - condition: state
        entity_id: device_tracker.phone_andrea_pixel
        state: 'home'
  action:
    service: homeassistant.turn_off
    entity_id: switch.lamp_garage_exterior_lights

#####
### Turn off Garage Exterior Lights at 04:30AM, if it's on
#####
- alias: 'Garage Exterior Lights Off'
  trigger:
    platform: time
    after: '04:30'
  condition:
    condition: state
    entity_id: switch.garage_exterior_lights
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.garage_exterior_lights
