- platform: template
  sensors:
    kitchen_door_status:
      friendly_name: 'Back Door'
      value_template: >-
          {%- if is_state("binary_sensor.door_kitchen_sensor_6_0", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_kitchen_sensor_6_0", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}

    kitchen_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.multisensor_kitchen_burglar_8_10", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}

    gunsafe_motion:
      friendly_name: 'Gun Safe'
      value_template: >-
          {%- if is_state("binary_sensor.multisensor_gunsafe_sensor_23_0", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.multisensor_gunsafe_sensor_23_0", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}

    ammosafe_door_status:
      friendly_name: 'Ammo Safe'
      value_template: >-
          {%- if is_state("binary_sensor.door_ammosafe_sensor_33_0", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_ammosafe_sensor_33_0", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}

    tvroom_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("binary_sensor.multisensor_tvroom_sensor_28_0", "off") -%}
              No
          {%- elif is_state("binary_sensor.multisensor_tvroom_sensor_28_0", "on") -%}
              Yes
          {%- else -%}
              FAILED
          {%- endif -%}

    office_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("binary_sensor.multisensor_office_sensor_38_0", "off") -%}
              No
          {%- elif is_state("binary_sensor.multisensor_office_sensor_38_0", "on") -%}
              Yes
          {%- else -%}
              FAILED
          {%- endif -%}

    sun_state:
      friendly_name: 'Sun State'
      value_template: >-
          {%- if is_state("sun.sun", "above_horizon") -%}
              Up
          {%- else -%}
              Down
          {%- endif -%}

    front_door_status:
      friendly_name: 'Front Door'
      value_template: >-
          {%- if is_state("sensor.door_front_access_control_13_9", "22") -%}
              Open
          {%- else -%}
              Closed
          {%- endif -%}

    garage_door_status:
      friendly_name: 'Garage Door'
      value_template: >-
          {%- if is_state("binary_sensor.tilt_garage_sensor_32_0", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.tilt_garage_sensor_32_0", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}

    climate_downstairs_temperature:
      friendly_name: 'Target Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {% if is_state('input_select.hvac_operation_mode_downstairs', 'Heat') %}
            {{ states.climate.thermostat_downstairs_heating_1_2_1.attributes.temperature }}
        {% elif is_state('input_select.hvac_operation_mode_downstairs', 'Cool') %}
            {{ states.climate.thermostat_downstairs_cooling_1_2_2.attributes.temperature }}
        {% else %}
            OFF
        {% endif %}

    climate_downstairs_batterylevel:
      friendly_name: 'Thermostat (Downstairs)'
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.thermostat_downstairs_relative_humidity_2_5_3.attributes.battery_level }}'

    climate_upstairs_temperature:
      friendly_name: 'Target Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {% if is_state('input_select.hvac_operation_mode_upstairs', 'Heat') %}
            {{ states.climate.thermostat_upstairs_heating_1_31_1.attributes.temperature }}
        {% elif is_state('input_select.hvac_operation_mode_upstairs', 'Cool') %}
            {{ states.climate.thermostat_upstairs_cooling_1_31_2.attributes.temperature }}
        {% else %}
            OFF
        {% endif %}      

    climate_upstairs_batterylevel:
      friendly_name: 'Thermostat (Upstairs)'
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.thermostat_upstairs_relative_humidity_31_5_3.attributes.battery_level }}'

    lock_deadbolt_kitchen_batterylevel:
      friendly_name: 'Deadbolt (Kitchen)'
      unit_of_measurement: '%'
      value_template: '{{ states.lock.deadbolt_kitchen_locked_9_0.attributes.battery_level }}'

    multisensor_kitchen_batterylevel:
      friendly_name: 'MultiSensor (Kitchen)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.multisensor_kitchen_sensor_8_0.attributes.battery_level }}'

    door_kitchen_batterylevel:
      friendly_name: 'Door Sensor (Kitchen)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.door_kitchen_sensor_6_0.attributes.battery_level }}'

    door_front_batterylevel:
      friendly_name: 'Door Sensor (Front)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.door_front_sensor_13_0.attributes.battery_level }}'

    door_ammosafe_batterylevel:
      friendly_name: 'Door Sensor (Ammo Safe)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.door_ammosafe_sensor_33_0.attributes.battery_level }}'

    multisensor_tvroom_batterylevel:
      friendly_name: 'MultiSensor (TV Room)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.multisensor_tvroom_sensor_28_0.attributes.battery_level }}'

    multisensor_office_batterylevel:
      friendly_name: 'MultiSensor (Office)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.multisensor_office_sensor_38_0.attributes.battery_level }}'

    tilt_garagedoor_batterylevel:
      friendly_name: 'Tilt Sensor (Garage Door)'
      unit_of_measurement: '%'
      value_template: '{{ states.binary_sensor.tilt_garage_sensor_32_0.attributes.battery_level }}'
